module.exports = {
  "CUSTOMERORDER": [
    {
      "PKEY": "73143976841",
      "ORDERDATE": "2021-07-21T00:00:00Z",
      "SITEID": "S02881",
      "LOBID": "O",
      "PLANDATE": "2021-07-21T00:00:00Z",
      "ASSIGNED": "X",
      "FK_SANDBOX_ROUTEORDER": [
        7314397680,
        7314397681,
        7314397683
      ],
      "FK_CUSTOMER": "3582010054",
      "CUSTOMERINFO": {
        "LASTDRIVERID": "193698",
        "CUSTOMERSITEID": "S02881",
        "UNIQUEID": "000217724673003",
        "COMPANYID": "O11",
        "COMPANYNUMBER": "0201433",
        "NAME": "DISTRIBUTION INTERNATIONAL G11",
        "CONTACT": "TONY",
        "FAX": "1235696",
        "PHONE": "7133572489",
        "EMAIL": "dist@wm.com",
        "RATING": "3",
        "FIRSTSERVICE": "2021-07-21T00:00:00Z",
        "SOURCE": "PS",
        "CUST_FOCUS_TIER": "3-Medium",
        "PREMIER_CUSTOMER": "Y",
        "REPEATE_HOC": "2",
        "HOC_CNT_CONT": "3"
      },
      "DETAILS": {
        "DHCODE": "DSP",
        "EXTHAUL": "X",
        "COMMENTS": "PLEASE PICKUP WASTE",
        "OTHERROUTEINFO": "",
        "MAS_STOP_KEY": "2563654",
        "MAS_TICKET_KEY": "521208081",
        "SCHEDULED": "X",
        "ISLINER": "X",
        "MAPCODE": "X",
        "MAPGRID": "X",
        "OPENEDBY": "mkshirsa",
        "REQUESTEDBY": "gwagh",
        "REQUESTEDDATE": "2021-07-21T00:00:00Z",
        "ENTEREDDATE": "2021-07-21T00:00:00Z",
        "WASTETYPE": "MSW",
        "OCCURENCEID": "E",
        "DSCODE": "ATL",
        "ERL_SEQUENCE": "X",
        "TICKETSOURCE": "MAS",
        "UOM": "T",
        "GUARANTEE_TYPE": "NA",
        "GUARANTEE_VALUE": "NA",
        "GUARANTEE_DESCRIPTION": "NA",
        "GUARANTEE_DATE": "2021-07-21T00:00:00Z",
        "BEGIN_SVCWINDOW1": "00:01:00",
        "END_SVCWINDOW1": "23:59:00",
        "BEGIN_SVCWINDOW2": "04:00:00",
        "END_SVCWINDOW2": "18:00:00",
        "MARKED_FOR_AUDIT": "X",
        "NEXTDAYTICKET": "699018",
        "MAS_RESPONSE": "SUCCESSFULLY UPDATED",
        "HOTCUSTOMER": "X",
        "CONTAINERONRAIL": "X",
        "SOURCE": "MAS",
        "ETA_REQUEST": "Y"
      },
      "SERVICELOCATION ": {
        "AUTO": {
          "HOUSE": "123",
          "STREET_NAME": "MG ROAD",
          "CITY_NAME": "HOUSTON",
          "ZIPCODE": "123-569",
          "REGION_NAME": "TX",
          "REGION_CODE": "TEXAS",
          "COUNTRY_NAME": "UNITED STATES",
          "COUNTRY_CODE": "US",
          "ADDITION": "X",
          "GEOQUALITY": "100",
          "LONGITUDE": "-12569789.36",
          "LATITUDE": "-6965696845.35",
          "SOURCE": "MAS"
        },
        "MANUAL": {
          "HOUSE": "123",
          "STREET_NAME": "MG ROAD",
          "CITY_NAME": "HOUSTON",
          "ZIPCODE": "123-569",
          "REGION_NAME": "TX",
          "REGION_CODE": "TEXAS",
          "COUNTRY_NAME": "UNITED STATES",
          "COUNTRY_CODE": "US",
          "ADDITION": "X",
          "GEOQUALITY": "100",
          "LONGITUDE": "-12569789.36",
          "LATITUDE": "-6965696845.35",
          "SOURCE": "MAS"
        }
      },
      "TICKETPRIORITY": "HIGH",
      "TICKETNUMBER": "319362",
      "ORDER_SEQUENCE": "1",
      "ROUTE_SEQUENCE": "000020",
      "TANDEM": "X",
      "FK_TANDEMCUSTOMERORDER": "5698569856",
      "TANDEMTICKETNUMBER": "319364",
      "FK_ORIGINALROUTEORDER": "7314397680",
      "LOADTYPE ": {
        "FIRST": "E/R",
        "PREVIOUS": "S/O",
        "CURRENT": "E/R"
      },
      "FK_LANDFILL": "2560",
      "LANDFILL": {
        "SITEID": "S02881",
        "ID": "ATL",
        "NAME": "ATAASCOCITA RDF",
        "INTERCOMPANY": "X",
        "INACTIVE": "X",
        "ADDRESS": {
          "HOUSE": "123",
          "STREET_NAME": "MG ROAD",
          "CITY_NAME": "HOUSTON",
          "ZIPCODE": "123-569",
          "REGION_NAME": "TX",
          "REGION_CODE": "TEXAS",
          "COUNTRY_NAME": "UNITED STATES",
          "COUNTRY_CODE": "US",
          "ADDITION": "X",
          "GEOQUALITY": "100",
          "LONGITUDE": "-12569789.36",
          "LATITUDE": "-6965696845.35",
          "SOURCE": "MAS"
        },
        "SHAPEID_OPERATIONAL": "c3223e27-22a0-46e4-9b45-36f72295cd84",
        "DISPOSAL_SITEID": "S04136",
        "DISPOSALINTEGRATION": "X",
        "DISPLAY_OBU": "X",
        "DA_DISPOSAL_DISPLAY": "ATAASCOCITA",
        "COMMODITY": "RDF"
      },
      "FK_PARENTCUSTOMERORDER ": "5698569858",
      "PARENTTICKETNUMBER ": "319360",
      "REASONCODE": "DEL",
      "CUSTOMER_NEW": "X",
      "CUSTOMER_CANCELED": "X",
      "CUSTOMER_CUTOFF": "X",
      "CANCELED": "X",
      "CLOSED": "X",
      "PROFILE_NUMBER": "966996TX",
      "PROFILE_DESCRIPTION": "Thermo-12 Gold",
      "SERVICETIME": "D",
      "WORKSTATUS": {
        "HISTORY": [
          {
            "CODE": "WORKING",
            "CREATED": "2021-02-24T10:20:23Z",
            "CODE_EXTENSION": "INLANDFILL",
            "USERNAME": "mkshirsa"
          }
        ],
        "ACTIVE": {
          "CODE": "CONFIRMED",
          "CREATED": "2021-02-24T10:20:23Z",
          "USERNAME": "mkshirsa"
        }
      },
      "TRANSMISSIONSTATUS": {
        "HISTORY": [
          {
            "CODE": "TRANSMITTED",
            "CREATED": "2021-02-24T10:20:23Z",
            "REFUSED": "X",
            "REFUSED_TEXT": "Any Text message",
            "ACKNOWLEDGE": "2021-02-24T10:25:23Z"
          }
        ],
        "ACTIVE": {
          "CODE": "RECALLED",
          "CREATED": "2021-02-24T10:20:23Z",
          "REFUSED": "X",
          "REFUSED_TEXT": "Any Text message",
          "ACKNOWLEDGE": "2021-02-24T10:25:23Z"
        }
      },
      "CUSTOMERSERVICES": [
        {
          "FK_SVCORGREASONCODE": "456789",
          "SVCORGREASONCODE": {
            "ID": "DEL",
            "TEXT": "DELIVERY (NON-CHARGEABLE)",
            "INACTIVE": "X",
            "PROP1": "X",
            "PROP2": "X",
            "PROP3": "X",
            "PROP4": "X",
            "PROP5": "X",
            "PROP6": "X",
            "PROP7": "X",
            "PROP8": "X",
            "PROP9": "X",
            "PROP10": "X",
            "PROP11": "X"
          },
          "FK_SVCREASONCODE": "123456",
          "SVCREASONCODE": {
            "ID": "REM",
            "TEXT": "REMOVAL (NON-CHARGEABLE)",
            "INACTIVE": "X",
            "PROP1": "X",
            "PROP2": "X",
            "PROP3": "X",
            "PROP4": "X",
            "PROP5": "X",
            "PROP6": "X",
            "PROP7": "X",
            "PROP8": "X",
            "PROP9": "X",
            "PROP10": "X",
            "PROP11": "X"
          },
          "SERVICEKEY": "1857820843000",
          "SRCUNIQUE_KEY": "STPRD-210129-5301-9720178686-2848338",
          "ID": "000000008",
          "CODE": "40C",
          "DESCR": "40 YD COMPACTOR",
          "SPDESCR": "DNR:1-10O",
          "QUANTITY": "1",
          "YARDS": "40",
          "BOX": "",
          "RECURRENCE": "X",
          "OCCURENCEID": "E",
          "INSTRUCTION": "ALL SVC REQUESTS MUST GO THROUGH NATIONAL ACCOUNTSPLEASE REMOVE THE 2 YARD",
          "CONTACT": "MANAGER ON DUTY",
          "PHONE": "7635617013",
          "SERVICEDQUANTITY": "1",
          "BULKDESCR": "BOXES",
          "PARENTSERVICEID": "000000006",
          "MANDISPOSALSITE": "false",
          "SWAPPABLE": "true",
          "SERVICETYPE": "H",
          "REPROPOSED": "U",
          "LOADTYPE": {
            "FIRST": "E/R",
            "PREVIOUS": "S/O",
            "CURRENT": "E/R"
          },
          "CNTRCLASSCODE": "10O",
          "CNTRCLASSDESC": "10 YARD OPEN TOP",
          "CONTAINERSIZE": "2 YD3",
          "CONTAINERTYPE": "CNT_FL",
          "MATERIAL": "MSW",
          "WHEELS": "YES",
          "LOCKS": "NO",
          "LIDS": "METAL",
          "OTHER": "SLANT",
          "TRUCK": "FL",
          "OCSCSPKEY": "5698653645"
        }
      ],
      "COSUMMARY": {
        "POST": {
          "CNT_CONTREPAIR": "1",
          "CNT_LANDFILL": "1",
          "CNT_WEIGHING": "1",
          "CNT_SIGNATURE": "1",
          "CNT_DOWNTIME": "1",
          "CNT_HOC": "3"
        }
      },
      "COSERVIECRESCHEDULE": [
        {
          "SERVICERESCHEDULE": {
            "ID": "1",
            "REASON_TEXT": "WM Rescheduled/Carryover",
            "REASON_TYPE": {
              "ID": "1",
              "TEXT": "Capacity: Personnel",
              "INACTIVE": "X",
              "PROP1": "X",
              "PROP2": "X",
              "PROP3": "X",
              "PROP4": "X",
              "PROP5": "X",
              "PROP6": "X",
              "PROP7": "X",
              "PROP8": "X",
              "PROP9": "X",
              "PROP10": "X",
              "PROP11": "X"
            },
            "SEND_CUSTOMERCOMM": "Y",
            "ISEXTERNAL": "Y",
            "INACTIVE": "N",
            "NOTIFYCATEGORY": {
              "ID": "1",
              "TEXT": "Servicereschedule-operations",
              "INACTIVE": "X",
              "PROP1": "X",
              "PROP2": "X",
              "PROP3": "X",
              "PROP4": "X",
              "PROP5": "X",
              "PROP6": "X",
              "PROP7": "X",
              "PROP8": "X",
              "PROP9": "X",
              "PROP10": "X",
              "PROP11": "X"
            },
            "SENDTOMAS": "Y"
          },
          "SERVICELOCATION": {
            "AUTO": {
              "HOUSE": "123",
              "STREET_NAME": "MG ROAD",
              "CITY_NAME": "HOUSTON",
              "ZIPCODE": "123-569",
              "REGION_NAME": "TX",
              "REGION_CODE": "TEXAS",
              "COUNTRY_NAME": "UNITED STATES",
              "COUNTRY_CODE": "US",
              "ADDITION": "X",
              "GEOQUALITY": "100",
              "LONGITUDE": "-12569789.36",
              "LATITUDE": "-6965696845.35",
              "SOURCE": "MAS"
            },
            "MANUAL": {
              "HOUSE": "123",
              "STREET_NAME": "MG ROAD",
              "CITY_NAME": "HOUSTON",
              "ZIPCODE": "123-569",
              "REGION_NAME": "TX",
              "REGION_CODE": "TEXAS",
              "COUNTRY_NAME": "UNITED STATES",
              "COUNTRY_CODE": "US",
              "ADDITION": "X",
              "GEOQUALITY": "100",
              "LONGITUDE": "-12569789.36",
              "LATITUDE": "-6965696845.35",
              "SOURCE": "MAS"
            }
          },
          "STATUS": "PROCESSED_ENQ",
          "MASTICKET": "319362",
          "CUSTUNIQUEID": "000217724673003",
          "FROMDATE": "2021-07-20T00:00:00Z",
          "TODATE": "2021-07-21T00:00:00Z",
          "RESCHEDULED_BY": "gwagh",
          "STAMP": "2021-07-20T10:20:23Z",
          "ACTIVE": "Y",
          "FROMROUTEORDER": "175644825",
          "TOROUTEORDER": "175644925",
          "TRANSACTION_ID": "56254356"
        }
      ],
      "OCSCOPKEY": "1234695683656"
    },
    {
      "PKEY": "7314397684",
      "ORDERDATE": "2021-07-21T00:00:00Z",
      "SITEID": "S02881",
      "LOBID": "O",
      "PLANDATE": "2021-07-21T00:00:00Z",
      "ASSIGNED": "X",
      "FK_SANDBOX_ROUTEORDER": [
        7314397680,
        7314397681,
        7314397683
      ],
      "FK_CUSTOMER": "3582010054",
      "CUSTOMERINFO": {
        "LASTDRIVERID": "193698",
        "CUSTOMERSITEID": "S02881",
        "UNIQUEID": "000217724673003",
        "COMPANYID": "O11",
        "COMPANYNUMBER": "0201433",
        "NAME": "DISTRIBUTION INTERNATIONAL G11",
        "CONTACT": "TONY",
        "FAX": "1235696",
        "PHONE": "7133572489",
        "EMAIL": "dist@wm.com",
        "RATING": "3",
        "FIRSTSERVICE": "2021-07-21T00:00:00Z",
        "SOURCE": "PS",
        "CUST_FOCUS_TIER": "3-Medium",
        "PREMIER_CUSTOMER": "Y",
        "REPEATE_HOC": "2",
        "HOC_CNT_CONT": "3"
      },
      "DETAILS": {
        "DHCODE": "DSP",
        "EXTHAUL": "X",
        "COMMENTS": "PLEASE PICKUP WASTE",
        "OTHERROUTEINFO": "",
        "MAS_STOP_KEY": "2563654",
        "MAS_TICKET_KEY": "521208081",
        "SCHEDULED": "X",
        "ISLINER": "X",
        "MAPCODE": "X",
        "MAPGRID": "X",
        "OPENEDBY": "mkshirsa",
        "REQUESTEDBY": "gwagh",
        "REQUESTEDDATE": "2021-07-21T00:00:00Z",
        "ENTEREDDATE": "2021-07-21T00:00:00Z",
        "WASTETYPE": "MSW",
        "OCCURENCEID": "E",
        "DSCODE": "ATL",
        "ERL_SEQUENCE": "X",
        "TICKETSOURCE": "MAS",
        "UOM": "T",
        "GUARANTEE_TYPE": "NA",
        "GUARANTEE_VALUE": "NA",
        "GUARANTEE_DESCRIPTION": "NA",
        "GUARANTEE_DATE": "2021-07-21T00:00:00Z",
        "BEGIN_SVCWINDOW1": "00:01:00",
        "END_SVCWINDOW1": "23:59:00",
        "BEGIN_SVCWINDOW2": "04:00:00",
        "END_SVCWINDOW2": "18:00:00",
        "MARKED_FOR_AUDIT": "X",
        "NEXTDAYTICKET": "699018",
        "MAS_RESPONSE": "SUCCESSFULLY UPDATED",
        "HOTCUSTOMER": "X",
        "CONTAINERONRAIL": "X",
        "SOURCE": "MAS",
        "ETA_REQUEST": "Y"
      },
      "SERVICELOCATION ": {
        "AUTO": {
          "HOUSE": "123",
          "STREET_NAME": "MG ROAD",
          "CITY_NAME": "HOUSTON",
          "ZIPCODE": "123-569",
          "REGION_NAME": "TX",
          "REGION_CODE": "TEXAS",
          "COUNTRY_NAME": "UNITED STATES",
          "COUNTRY_CODE": "US",
          "ADDITION": "X",
          "GEOQUALITY": "100",
          "LONGITUDE": "-12569789.36",
          "LATITUDE": "-6965696845.35",
          "SOURCE": "MAS"
        },
        "MANUAL": {
          "HOUSE": "123",
          "STREET_NAME": "MG ROAD",
          "CITY_NAME": "HOUSTON",
          "ZIPCODE": "123-569",
          "REGION_NAME": "TX",
          "REGION_CODE": "TEXAS",
          "COUNTRY_NAME": "UNITED STATES",
          "COUNTRY_CODE": "US",
          "ADDITION": "X",
          "GEOQUALITY": "100",
          "LONGITUDE": "-12569789.36",
          "LATITUDE": "-6965696845.35",
          "SOURCE": "MAS"
        }
      },
      "TICKETPRIORITY": "HIGH",
      "TICKETNUMBER": "319362",
      "ORDER_SEQUENCE": "1",
      "ROUTE_SEQUENCE": "000020",
      "TANDEM": "X",
      "FK_TANDEMCUSTOMERORDER": "5698569856",
      "TANDEMTICKETNUMBER": "319364",
      "FK_ORIGINALROUTEORDER": "7314397680",
      "LOADTYPE ": {
        "FIRST": "E/R",
        "PREVIOUS": "S/O",
        "CURRENT": "E/R"
      },
      "FK_LANDFILL": "2560",
      "LANDFILL": {
        "SITEID": "S02881",
        "ID": "ATL",
        "NAME": "ATAASCOCITA RDF",
        "INTERCOMPANY": "X",
        "INACTIVE": "X",
        "ADDRESS": {
          "HOUSE": "123",
          "STREET_NAME": "MG ROAD",
          "CITY_NAME": "HOUSTON",
          "ZIPCODE": "123-569",
          "REGION_NAME": "TX",
          "REGION_CODE": "TEXAS",
          "COUNTRY_NAME": "UNITED STATES",
          "COUNTRY_CODE": "US",
          "ADDITION": "X",
          "GEOQUALITY": "100",
          "LONGITUDE": "-12569789.36",
          "LATITUDE": "-6965696845.35",
          "SOURCE": "MAS"
        },
        "SHAPEID_OPERATIONAL": "c3223e27-22a0-46e4-9b45-36f72295cd84",
        "DISPOSAL_SITEID": "S04136",
        "DISPOSALINTEGRATION": "X",
        "DISPLAY_OBU": "X",
        "DA_DISPOSAL_DISPLAY": "ATAASCOCITA",
        "COMMODITY": "RDF"
      },
      "FK_PARENTCUSTOMERORDER ": "5698569858",
      "PARENTTICKETNUMBER ": "319360",
      "REASONCODE": "DEL",
      "CUSTOMER_NEW": "X",
      "CUSTOMER_CANCELED": "X",
      "CUSTOMER_CUTOFF": "X",
      "CANCELED": "X",
      "CLOSED": "X",
      "PROFILE_NUMBER": "966996TX",
      "PROFILE_DESCRIPTION": "Thermo-12 Gold",
      "SERVICETIME": "D",
      "WORKSTATUS": {
        "HISTORY": [
          {
            "CODE": "WORKING",
            "CREATED": "2021-02-24T10:20:23Z",
            "CODE_EXTENSION": "INLANDFILL",
            "USERNAME": "mkshirsa"
          }
        ],
        "ACTIVE": {
          "CODE": "CONFIRMED",
          "CREATED": "2021-02-24T10:20:23Z",
          "USERNAME": "mkshirsa"
        }
      },
      "TRANSMISSIONSTATUS": {
        "HISTORY": [
          {
            "CODE": "TRANSMITTED",
            "CREATED": "2021-02-24T10:20:23Z",
            "REFUSED": "X",
            "REFUSED_TEXT": "Any Text message",
            "ACKNOWLEDGE": "2021-02-24T10:25:23Z"
          }
        ],
        "ACTIVE": {
          "CODE": "RECALLED",
          "CREATED": "2021-02-24T10:20:23Z",
          "REFUSED": "X",
          "REFUSED_TEXT": "Any Text message",
          "ACKNOWLEDGE": "2021-02-24T10:25:23Z"
        }
      },
      "CUSTOMERSERVICES": [
        {
          "FK_SVCORGREASONCODE": "456789",
          "SVCORGREASONCODE": {
            "ID": "DEL",
            "TEXT": "DELIVERY (NON-CHARGEABLE)",
            "INACTIVE": "X",
            "PROP1": "X",
            "PROP2": "X",
            "PROP3": "X",
            "PROP4": "X",
            "PROP5": "X",
            "PROP6": "X",
            "PROP7": "X",
            "PROP8": "X",
            "PROP9": "X",
            "PROP10": "X",
            "PROP11": "X"
          },
          "FK_SVCREASONCODE": "123456",
          "SVCREASONCODE": {
            "ID": "REM",
            "TEXT": "REMOVAL (NON-CHARGEABLE)",
            "INACTIVE": "X",
            "PROP1": "X",
            "PROP2": "X",
            "PROP3": "X",
            "PROP4": "X",
            "PROP5": "X",
            "PROP6": "X",
            "PROP7": "X",
            "PROP8": "X",
            "PROP9": "X",
            "PROP10": "X",
            "PROP11": "X"
          },
          "SERVICEKEY": "1857820843000",
          "SRCUNIQUE_KEY": "STPRD-210129-5301-9720178686-2848338",
          "ID": "000000008",
          "CODE": "40C",
          "DESCR": "40 YD COMPACTOR",
          "SPDESCR": "DNR:1-10O",
          "QUANTITY": "1",
          "YARDS": "40",
          "BOX": "",
          "RECURRENCE": "X",
          "OCCURENCEID": "E",
          "INSTRUCTION": "ALL SVC REQUESTS MUST GO THROUGH NATIONAL ACCOUNTSPLEASE REMOVE THE 2 YARD",
          "CONTACT": "MANAGER ON DUTY",
          "PHONE": "7635617013",
          "SERVICEDQUANTITY": "1",
          "BULKDESCR": "BOXES",
          "PARENTSERVICEID": "000000006",
          "MANDISPOSALSITE": "false",
          "SWAPPABLE": "true",
          "SERVICETYPE": "H",
          "REPROPOSED": "U",
          "LOADTYPE": {
            "FIRST": "E/R",
            "PREVIOUS": "S/O",
            "CURRENT": "E/R"
          },
          "CNTRCLASSCODE": "10O",
          "CNTRCLASSDESC": "10 YARD OPEN TOP",
          "CONTAINERSIZE": "2 YD3",
          "CONTAINERTYPE": "CNT_FL",
          "MATERIAL": "MSW",
          "WHEELS": "YES",
          "LOCKS": "NO",
          "LIDS": "METAL",
          "OTHER": "SLANT",
          "TRUCK": "FL",
          "OCSCSPKEY": "5698653645"
        }
      ],
      "COSUMMARY": {
        "POST": {
          "CNT_CONTREPAIR": "1",
          "CNT_LANDFILL": "1",
          "CNT_WEIGHING": "1",
          "CNT_SIGNATURE": "1",
          "CNT_DOWNTIME": "1",
          "CNT_HOC": "3"
        }
      },
      "COSERVIECRESCHEDULE": [
        {
          "SERVICERESCHEDULE": {
            "ID": "1",
            "REASON_TEXT": "WM Rescheduled/Carryover",
            "REASON_TYPE": {
              "ID": "1",
              "TEXT": "Capacity: Personnel",
              "INACTIVE": "X",
              "PROP1": "X",
              "PROP2": "X",
              "PROP3": "X",
              "PROP4": "X",
              "PROP5": "X",
              "PROP6": "X",
              "PROP7": "X",
              "PROP8": "X",
              "PROP9": "X",
              "PROP10": "X",
              "PROP11": "X"
            },
            "SEND_CUSTOMERCOMM": "Y",
            "ISEXTERNAL": "Y",
            "INACTIVE": "N",
            "NOTIFYCATEGORY": {
              "ID": "1",
              "TEXT": "Servicereschedule-operations",
              "INACTIVE": "X",
              "PROP1": "X",
              "PROP2": "X",
              "PROP3": "X",
              "PROP4": "X",
              "PROP5": "X",
              "PROP6": "X",
              "PROP7": "X",
              "PROP8": "X",
              "PROP9": "X",
              "PROP10": "X",
              "PROP11": "X"
            },
            "SENDTOMAS": "Y"
          },
          "SERVICELOCATION": {
            "AUTO": {
              "HOUSE": "123",
              "STREET_NAME": "MG ROAD",
              "CITY_NAME": "HOUSTON",
              "ZIPCODE": "123-569",
              "REGION_NAME": "TX",
              "REGION_CODE": "TEXAS",
              "COUNTRY_NAME": "UNITED STATES",
              "COUNTRY_CODE": "US",
              "ADDITION": "X",
              "GEOQUALITY": "100",
              "LONGITUDE": "-12569789.36",
              "LATITUDE": "-6965696845.35",
              "SOURCE": "MAS"
            },
            "MANUAL": {
              "HOUSE": "123",
              "STREET_NAME": "MG ROAD",
              "CITY_NAME": "HOUSTON",
              "ZIPCODE": "123-569",
              "REGION_NAME": "TX",
              "REGION_CODE": "TEXAS",
              "COUNTRY_NAME": "UNITED STATES",
              "COUNTRY_CODE": "US",
              "ADDITION": "X",
              "GEOQUALITY": "100",
              "LONGITUDE": "-12569789.36",
              "LATITUDE": "-6965696845.35",
              "SOURCE": "MAS"
            }
          },
          "STATUS": "PROCESSED_ENQ",
          "MASTICKET": "319362",
          "CUSTUNIQUEID": "000217724673003",
          "FROMDATE": "2021-07-20T00:00:00Z",
          "TODATE": "2021-07-21T00:00:00Z",
          "RESCHEDULED_BY": "gwagh",
          "STAMP": "2021-07-20T10:20:23Z",
          "ACTIVE": "Y",
          "FROMROUTEORDER": "175644825",
          "TOROUTEORDER": "175644925",
          "TRANSACTION_ID": "56254356"
        }
      ],
      "OCSCOPKEY": "1234695683656"
    }
  ]
}